#!/bin/bash -x
#SBATCH --account=hai_1223
#SBATCH --cpus-per-task=12
#SBATCH --ntasks=4
#SBATCH --gres=gpu:4
#SBATCH --output=out/output.%j
#SBATCH --error=err/error.%j
#SBATCH --time=24:00:00
#SBATCH --partition=booster

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export SRUN_CPUS_PER_TASK="$SLURM_CPUS_PER_TASK"

# NCCL / distributed
export MASTER_ADDR=$(scontrol show hostname "$SLURM_NODELIST" | head -n 1)
export MASTER_PORT=29500
export NCCL_DEBUG=INFO
export TORCH_NCCL_BLOCKING_WAIT=1
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1

# activate env
source ../../venv_setup/activate.sh

# run
time torchrun \
  --nnodes=$SLURM_JOB_NUM_NODES \
  --nproc_per_node=4 \
  --rdzv_id=$SLURM_JOB_ID \
  --rdzv_backend=c10d \
  --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT \
   train.py \
    --train_csv_path ../../data/pretraining/dataset_with_utr3/train.csv \
    --test_csv_path ../../data/pretraining/dataset_with_utr3/test.csv \
    --output_path ../../data/models/lo_arm_high_lr/lo_arm_pretrained.pt \
    --checkpoint_path ../../data/models/lo_arm_high_lr/lo_arm_pretrained.pt \
    --n_layers 6 \
    --d_model 256 \
    --n_heads 8 \
    --batch_size 256 \
    --learning_rate 5e-5 \
    --weight_decay 0.01 \
    --grad_clip 1.0 \
    --epochs 80 \
    --wandb
