#!/bin/bash -x
#SBATCH --account=hai_1223  	 	     # Account details
#SBATCH --cpus-per-task=12
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1                    # 4 GPUs, 1 per task
#SBATCH --output=out/output.%j               # File for standard output
#SBATCH --error=err/error.%j                 # File for standard error
#SBATCH --time=00:10:00                  # Maximum runtime
#SBATCH --partition=booster              # Specified machine partition

# To get number of cpu per task
export SRUN_CPUS_PER_TASK="$SLURM_CPUS_PER_TASK"

export WANDB_API_KEY="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"
export WANDB_MODE=offline

# activate env
source ../../venv_setup/activate.sh


export WANDB_API_KEY="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"


# run script 
time srun python3 finetune.py \
    --csv_path ../../data/finetuning/ribonn/dataset.csv \
    --batch_size 8 \
    --epochs 2 \
    --output_path checkpoints/test_model.pth \
    --pretrained_path /p/project1/hai_1223/olejnik1/TeamML-mRNA-project/data/models/indigo_pretrain.pt \
    --gen_order sao \
    --ribonn_weights_folder ../../data/ribonn_weights/weights/human \
    --ribonn_top_k 4 \
    --lambda_ribonn 0.05 \
    --wandb \
    --wandb_project indigo-finetuning-jagoda

