#!/bin/bash -x
#SBATCH --account=hai_1223  	 	     # Account details
#SBATCH --cpus-per-task=12
#SBATCH --ntasks=4
#SBATCH --gres=gpu:4                     # 4 GPUs, 1 per task
#SBATCH --output=out/output.%j               # File for standard output
#SBATCH --error=err/error.%j                 # File for standard error
#SBATCH --time=00:05:00                  # Maximum runtime
#SBATCH --partition=booster              # Specified machine partition

# To get number of cpu per task
export SRUN_CPUS_PER_TASK="$SLURM_CPUS_PER_TASK"

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT/src/models/indigo"
source "$REPO_ROOT/venv_setup/activate.sh"
export PYTHONPATH="$REPO_ROOT${PYTHONPATH:+:$PYTHONPATH}"

# time srun python3 -m src.models.indigo.pretrain --wandb --gen_order l2r
time srun python3 -m src.models.indigo.pretrain --wandb --gen_order sao --sao_beam_size 4 --sao_tokens_per_step 10
