#!/bin/bash -x
#SBATCH --account=hai_1223  	 	     # Account details
#SBATCH --cpus-per-task=12
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1                     # 4 GPUs, 1 per task
#SBATCH --output=out/output.%j               # File for standard output
#SBATCH --error=err/error.%j                 # File for standard error
#SBATCH --time=00:10:00                  # Maximum runtime
#SBATCH --partition=booster              # Specified machine partition

# To get number of cpu per task
export SRUN_CPUS_PER_TASK="$SLURM_CPUS_PER_TASK"

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT/src/models/indigo"
source "$REPO_ROOT/venv_setup/activate.sh"
export PYTHONPATH="$REPO_ROOT${PYTHONPATH:+:$PYTHONPATH}"

time srun python3 -m src.models.indigo.finetune \
    --csv_path ../../data/finetuning/ribonn/dataset.csv \
    --ribonn_weights_folder ../../data/ribonn_weights/weights/human \
    --lambda_ribonn 0.05 \
    --gen_order sao \
    --subset 128 \
    --batch_size 4 \
    --epochs 10 \
    --output_path checkpoints/test_model.pth
