#!/bin/bash -x
#SBATCH --account=hai_1223  	 	     # Account details
#SBATCH --cpus-per-task=48
#SBATCH --gres=gpu:1                     # Use the 4 GPUs available
#SBATCH --output=out/output.%j               # File for standard output
#SBATCH --error=err/error.%j                 # File for standard error
#SBATCH --time=10:00:00                  # Maximum runtime
#SBATCH --partition=booster              # Specified machine partition

# To get number of cpu per task
export SRUN_CPUS_PER_TASK="$SLURM_CPUS_PER_TASK"

# activate env
source ../../venv_setup/activate.sh

# run script 
# time srun python3 pretrain.py --output_path model_state_dict/utr53_pretrained.pt
    # --csv_path ../../data/finetuning/ribonn/ribonn_human.xlsx \
time srun python3 finetune.py \
    --csv_path ../../data/finetuning/ribonn/dataset.csv \
    --pretrained_path model_state_dict/utr53_pretrained.pt \
    --output_path model_state_dict/finetuning_checkpoint.pt \
    --ribonn_weights_folder ../../RiboNN/models/human \
    --ribonn_top_k 5 \
    --wandb
    
