#!/bin/bash -x
#SBATCH --account=hai_1223  	 	     # Account details
#SBATCH --cpus-per-task=48
#SBATCH --gres=gpu:1                     
#SBATCH --time=12:00:00                  # Maximum runtime
#SBATCH --partition=booster              # Specified machine partition
#SBATCH --output=out/out_%A_%a.txt
#SBATCH --error=err/err_%A_%a.txt
#SBATCH --array=0-11%8

# To get number of cpu per task
export SRUN_CPUS_PER_TASK="$SLURM_CPUS_PER_TASK"

# activate env
source ../../venv_setup/activate.sh

nlayers=(2 4 6)
nheads=(4 8)
lrs=(1e-4 3e-4)

lr_idx=$((SLURM_ARRAY_TASK_ID / 6))
heads_idx=$((SLURM_ARRAY_TASK_ID % 2))
layers_idx=$(((SLURM_ARRAY_TASK_ID / 2) % 3))

LR=${lrs[$lr_idx]}
HEADS=${nheads[$heads_idx]}
LAYERS=${nlayers[$layers_idx]}

echo "Running with LR=$LR, HEADS=$HEADS LAYERS=$LAYERS"

# run script 
time srun python3 pretrain.py --wandb --n_layers $LAYERS --n_heads $HEADS --learning_rate $LR
