#!/bin/bash
#SBATCH --job-name=bml_project_2gpu
#SBATCH --nodes=1
#SBATCH --time=00:05:00
#SBATCH --account=plgpkattenion-gpu-a100
#SBATCH --partition=plgrid-gpu-a100
#SBATCH --gres=gpu:2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=125G
#SBATCH --output=logs/%x_%j.out
#SBATCH --error=logs/%x_%j.err

cd /net/tscratch/people/plgmbmolas/
source venv/bin/activate

torchrun --nnodes=1 --nproc_per_node=2 main.py \
  --n_layers 4 \
  --d_model 256 \
  --n_heads 4 \
  --batch_size 64 \
  --n_training_steps 1000
