samples_csv: /Users/pawel/TeamML-mRNA-project/data/evals/test_500_pretrained_0423/generated_samples_100.csv
eval_dir: /Users/pawel/TeamML-mRNA-project/data/evals/scorer_test

scorers:
  string_statistics: {}
  ribonn:
    weights_path: RiboNN/models/human/a569cb3e25b24729aa634dfc0c58635c/state_dict.pth
    # weights_folder: RiboNN/models/human
    top_k_models_to_use: 5
    # batch_size: 32
  utrlm: {}
  rnafold: {}

plots:
  gt_vs_generated_distribution:
    metrics: {}
