samples_csv: /Users/pawel/TeamML-mRNA-project/data/evals/test_500_pretrained_0423/generated_samples.csv
save_dir: /Users/pawel/TeamML-mRNA-project/data/evals/scorer_test
scorers:
  string_statistics: {}
  ribonn: {}
    # weights_folder: RiboNN/models/human
    # top_k_models_to_use: 5
    # batch_size: 32
  utrlm: {}

