#!/bin/bash -x
#SBATCH --account=hai_1223
#SBATCH --job-name=pretrain_fsdp
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4         # 1 process per GPU
#SBATCH --gres=gpu:4
#SBATCH --cpus-per-task=12
#SBATCH --output=out/output.%j
#SBATCH --error=err/error.%j
#SBATCH --time=24:00:00
#SBATCH --partition=booster

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export SRUN_CPUS_PER_TASK="$SLURM_CPUS_PER_TASK"

# NCCL / distributed
export MASTER_ADDR=$(scontrol show hostname "$SLURM_NODELIST" | head -n 1)
export MASTER_PORT=29500
export NCCL_DEBUG=INFO
export TORCH_NCCL_BLOCKING_WAIT=1
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1

# activate env
source ../../venv_setup/activate.sh

# run
time torchrun \
  --nnodes=$SLURM_JOB_NUM_NODES \
  --nproc_per_node=4 \
  --rdzv_id=$SLURM_JOB_ID \
  --rdzv_backend=c10d \
  --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT \
  pretrain.py \
    --wandb \
    --gen_order sao \
    --sao_beam_size 4 \
    --sao_tokens_per_step 20 \
    --epochs 10 \
    --n_heads 4 \
    --n_layers 3 \
    --learning_rate 3e-4 \
    --output_path ./model_state_dict/dist_indigo_skinny_step2.pt \
    --checkpoint_path ./model_state_dict/dist_indigo_skinny.pt